# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "APov74vpttrduJPskYs7QlEQ8iKTffTqf2G92rT2eHrNxyDaOaeREmqxejBVBXIkczXnb9ZVu+mnfsVYOERjtgwYmdOw61MKpuwLt2OfwWE5PASHTeaGgPEtDv4NcboHvR9fyd35bToCHklF6QqUUz3+I5xmvxCw8NzBbF9ubQbXmOVTz0peXx5c0hyZoV52Zmnmmqh9pREnEvZoU3zl0Qn7nVfiBq5wQKjl0BWTq3gTfzPYXfyVHFmcH2i1aAArLEx1TRTGvbBCqL3lcaJCitxKm88trygZt54sEsKZ1n3dVhuOCPKDWPEGRIMW5LzdGJg658okbUFZQrmI0HKYD+9GdfN/gDBTiy74NS1FFDwBPZMWm3pzIvadt7sJBZMZQ86Ku1mON9zRUEuFeGxa8n6CruS1hWO4cG5bL4p2coUQq4VZ/VwDzqIHuRN8mO0b03tt/v5Igk/l1LivaUKwpE5kuFj2CdpZmd4yId0z8qj5OVDI6sym6UhEiWZw0h0vIHbzX0ZcjX0kGMZeqNkGfctLgTCXwFRJFCGvUdrGuEshmJZP4hKS3BTWUM0PMCuNghZpBv9xsmDp+r4qaZRtpVlJCMuFfpR9mbF3iXyt5p0v7RNZcNnU/sB3zG3HeW23MRJo7IYqGjUNdeVAy5tIVKeoe/XiBs2BMxzpD8C3KEY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
